name: Deploy Umanaged Application
run-name: Packing ${{ github.event.inputs.solution_name }} for ${{ github.event.inputs.environment_url }} environment
on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: "name of the Solution"
        required: true
        default: PowerAppsTools_lic
      # environment_id:
      #   description: "GUID of your Dataverse environment"
      #   required: true
      #   default: "GUID-OF-YOUR-ENVIRONMENT"
      environment_url:
        description: "http endpoint of your Dataverse environment"
        required: true
        default: "https://orged15bcc0.crm.dynamics.com"  # Test Environment URL
      #solution_source_folder:
       # description: "Location of the solution files"
        #requried: true
        #default: .
      #solution_outbound_folder:
       # description: "solution outbound folder"
        #required: true
        #default: out/stage
env:
#edit your values here
  CLIENT_ID: 'c4f9845e-0c18-47a0-8c0a-dbaf0805db8f'
  TENANT_ID: 'ffd09dde-3ff4-494d-9a02-3e6b9de29e35'

permissions:
  contents: write
  
jobs:
    pack-umanaged-solution-import:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
        env:
          RUNNER_DEBUG: 1
      
       
      - name: Pack the solution
        uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          # solution-folder: ${{ github.event.repository.name}}/${{ github.event.inputs.solution_name }}
          solution-folder: out/solutions/${{ github.event.inputs.solution_name }}
          # solution-file: ${{ github.event.repository.name}}/${{ github.event.inputs.solution_name }}.zip
          solution-file: out/exported/${{ github.event.inputs.solution_name }}_unmanaged.zip
          solution-type: Unmanaged
    
      - name: Import solution as unmanaged to build env
        uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: ${{github.event.inputs.environment_url}}
          app-id: ${{env.CLIENT_ID}}
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: ${{env.TENANT_ID}}
          # solution-file: ${{ github.event.repository.name}}/${{ github.event.inputs.solution_name }}.zip
          solution-file: out/exported/${{ github.event.inputs.solution_name }}_unmanaged.zip
          force-overwrite: true
          publish-changes: true
    
